version: '2'
services:
  openmeetrecorder-app:
    image: openmeetrecorder
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://openmeetrecorder-postgresql:5432/openmeetrecorder
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://openmeetrecorder-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://openmeetrecorder-elasticsearch:9200
    ports:
      - 8080:8080
  openmeetrecorder-postgresql:
    extends:
      file: postgresql.yml
      service: openmeetrecorder-postgresql
  openmeetrecorder-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: openmeetrecorder-elasticsearch
